
services:

  mariadb: 
    container_name: mariadb
    env_file: 
      - ./.env
    volumes: 
      - /var/lib/mysql
    build: ./requirements/mariadb
    image: mariadb:user
    restart: always
    networks:
      - inception
    command: sh -c "/usr/local/bin/mdb_conf.sh && exec mariadb"

  nginx:
    build: ./requirements/nginx
    image: nginx:user
    container_name: nginx
    ports: 
      - "443:443"
    volumes: 
      - /var/www/wordpress
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:user
    container_name: wordpress
    env_file: 
      - ./.env
    volumes: 
      - /var/www/wordpress
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception

volumes:
  mariadb:
    name: mariadb
    driver: bind
    driver_opts:
      device: /home/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: bind
    driver_opts:
      device: /home/data/wordpress
      o: bind
      type: none


networks:
  inception:
    name: inception
    driver: bridge
